package com.example.throwupthursday;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.throwupthursday.daos.Person;

import java.util.ArrayList;

import com.example.throwupthursday.PersonRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/people") // This means URL's start with /demo (after Application path)
public class PersonController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonRepository personRepository;
    
    // first get a single object return working
    @GetMapping(path="/getconst")
    public @ResponseBody Person getSingleUser() {
        // This returns a single new Person object.
        Person n = new Person();
        n.setName("Joe");
        n.setAge(23);
        return n;
    }

   // second get a single object iterable return working
   @GetMapping(path="/getiter")
   public @ResponseBody Iterable<Person> getSingleIter() {
       // This returns a single constant object within an ArrayList that is Iterable.
       Person n = new Person();
       n.setName("Joe");
       n.setAge(23);
       ArrayList<Person> tempList = new ArrayList<>();
       tempList.add(n);
       return tempList;
   }

   // third get result of a repo call working
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Person> getAllUsers() {
        // This returns a JSON or XML with the users
        return personRepository.findAll();
    }

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam Integer age) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Person n = new Person();
        n.setName(name);
        n.setAge(age);
        personRepository.save(n);
        return "Saved";
    }
}

// $ curl 'localhost:8080/people/add?name=George&age=28'